version: '3.8'

services:
  api:
    platform: linux/amd64
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    # env_file:
    #   - .env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/api
    command: yarn start:dev
    ports:
      - 3000:3000
      - 5555:5555
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.d:/docker-entrypoint-initdb.d
      - ./docker/postgres/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: postgres
      TZ: Asia/Tokyo
    hostname: postgres
    restart: always
    user: root
