version: '3.8'

services:
  api:
    platform: linux/amd64
    container_name: api
    build:
      dockerfile: Dockerfile
      context: .
    # env_file:
    #   - .env
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/api
    # command: sh -c "yarn start:dev"
    command: yarn start:dev
    ports:
      - 3000:3000
      - 5555:5555
    tty: true
    # depends_on:
    #   - postgres

  # postgres:
  #   image: postgres:14-alpine
  #   container_name: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: udemy
  #     TZ: 'Asia/Tokyo'
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./db/postgres/data:/var/lib/postgresql/data
